//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibraries.Database
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class agvStationTestFlow
    {
        public int Id { get; set; }
        public string Zone { get; set; }
        public string Station_Location { get; set; }
        public string Station_Name { get; set; }
        public string Dest_Station { get; set; }
        public string Idle_Area { get; set; }
        public string Remark { get; set; }
    }
}
